version: '3'
services:
  mysql:
    image: mysql:latest
    restart: always
    environment:
      - MYSQL_USER=test
      - MYSQL_ROOT_PASSWORD=1234
      - MYSQL_DATABASE=hhplus-local
      - TZ=Asia/Seoul
    hostname: localhost
    ports:
      - "3306:3306"
